"""
Comprehensive tests for calculator module.

Generated by Automated Testing Plugin v2.0
Test Location: tests/ (discoverable by pytest)
"""

import pytest
from src.calculator import add, subtract, multiply, divide


class TestAdd:
    """Tests for add() function."""

    def test_add_positive_numbers(self):
        """Test adding two positive numbers."""
        # Arrange
        a, b = 5, 3

        # Act
        result = add(a, b)

        # Assert
        assert result == 8

    def test_add_negative_numbers(self):
        """Test adding two negative numbers."""
        # Arrange
        a, b = -5, -3

        # Act
        result = add(a, b)

        # Assert
        assert result == -8

    def test_add_mixed_signs(self):
        """Test adding positive and negative numbers."""
        # Arrange
        a, b = 10, -3

        # Act
        result = add(a, b)

        # Assert
        assert result == 7

    def test_add_with_zero(self):
        """Test adding zero."""
        # Arrange
        a, b = 5, 0

        # Act
        result = add(a, b)

        # Assert
        assert result == 5

    def test_add_floats(self):
        """Test adding floating point numbers."""
        # Arrange
        a, b = 2.5, 3.7

        # Act
        result = add(a, b)

        # Assert
        assert result == pytest.approx(6.2)


class TestSubtract:
    """Tests for subtract() function."""

    def test_subtract_positive_numbers(self):
        """Test subtracting two positive numbers."""
        # Arrange
        a, b = 10, 3

        # Act
        result = subtract(a, b)

        # Assert
        assert result == 7

    def test_subtract_to_negative(self):
        """Test subtraction resulting in negative."""
        # Arrange
        a, b = 5, 10

        # Act
        result = subtract(a, b)

        # Assert
        assert result == -5

    def test_subtract_zero(self):
        """Test subtracting zero."""
        # Arrange
        a, b = 5, 0

        # Act
        result = subtract(a, b)

        # Assert
        assert result == 5

    def test_subtract_floats(self):
        """Test subtracting floating point numbers."""
        # Arrange
        a, b = 7.5, 2.5

        # Act
        result = subtract(a, b)

        # Assert
        assert result == pytest.approx(5.0)


class TestMultiply:
    """Tests for multiply() function."""

    def test_multiply_positive_numbers(self):
        """Test multiplying two positive numbers."""
        # Arrange
        a, b = 4, 5

        # Act
        result = multiply(a, b)

        # Assert
        assert result == 20

    def test_multiply_by_zero(self):
        """Test multiplying by zero."""
        # Arrange
        a, b = 5, 0

        # Act
        result = multiply(a, b)

        # Assert
        assert result == 0

    def test_multiply_negative_numbers(self):
        """Test multiplying negative numbers."""
        # Arrange
        a, b = -3, -4

        # Act
        result = multiply(a, b)

        # Assert
        assert result == 12

    def test_multiply_mixed_signs(self):
        """Test multiplying positive and negative."""
        # Arrange
        a, b = -5, 3

        # Act
        result = multiply(a, b)

        # Assert
        assert result == -15

    def test_multiply_floats(self):
        """Test multiplying floating point numbers."""
        # Arrange
        a, b = 2.5, 4

        # Act
        result = multiply(a, b)

        # Assert
        assert result == pytest.approx(10.0)


class TestDivide:
    """Tests for divide() function."""

    def test_divide_positive_numbers(self):
        """Test dividing two positive numbers."""
        # Arrange
        a, b = 10, 2

        # Act
        result = divide(a, b)

        # Assert
        assert result == pytest.approx(5.0)

    def test_divide_to_float(self):
        """Test division resulting in float."""
        # Arrange
        a, b = 7, 2

        # Act
        result = divide(a, b)

        # Assert
        assert result == pytest.approx(3.5)

    def test_divide_negative_numbers(self):
        """Test dividing negative numbers."""
        # Arrange
        a, b = -10, 2

        # Act
        result = divide(a, b)

        # Assert
        assert result == pytest.approx(-5.0)

    def test_divide_by_zero_raises_error(self):
        """Test that dividing by zero raises ValueError."""
        # Arrange
        a, b = 5, 0

        # Act & Assert
        with pytest.raises(ValueError, match="Cannot divide by zero"):
            divide(a, b)

    def test_divide_zero_by_number(self):
        """Test dividing zero by a number."""
        # Arrange
        a, b = 0, 5

        # Act
        result = divide(a, b)

        # Assert
        assert result == pytest.approx(0.0)
